const data = [
	{
		state: 'domisili',
		url: 'domisili',
		label: 'Domisili',
		style: 'single',
		column: 1,
	},
	{
		state: 'hubunganWali',
		url: 'hubungan-wali',
		label: 'Hubungan Wali',
		style: 'single',
		column: 1,
	},
	{
		state: 'jabatanMadrasiyah',
		url: 'jabatan-madrasiyah',
		label: 'Jabatan Madrasiyah',
		style: 'single',
		column: 1,
	},
	{
		state: 'kelas',
		url: 'kelas',
		label: 'Kelas',
		style: 'single',
		column: 1,
	},
	{
		state: 'keteranganIuran',
		url: 'keterangan-iuran',
		label: 'Keterangan Iuran',
		style: 'single',
		column: 1,
	},
	{
		state: 'keteranganIzin',
		url: 'keterangan-izin',
		label: 'Keterangan Izin',
		style: 'single',
		column: 1,
	},
	{
		state: 'keteranganStatus',
		url: 'keterangan-status',
		label: 'Keterangan Status',
		style: 'single',
		column: 1,
	},
	{
		state: 'metodePembayaran',
		url: 'metode-pembayaran',
		label: 'Metode Pembayaran',
		style: 'single',
		column: 1,
	},
	{
		state: 'pekerjaan',
		url: 'pekerjaan',
		label: 'Pekerjaan',
		style: 'single',
		column: 1,
	},
	{
		state: 'jenisLembagaPendidikan',
		url: 'jenis-lembaga-pendidikan',
		label: 'Jenis Lembaga Pendidikan',
		style: 'single',
		column: 1,
	},
	{
		state: 'wilayahUgt',
		url: 'wilayah-ugt',
		label: 'Wilayah UGT',
		style: 'single',
		column: 1,
	},
	{
		state: 'pa_Diniyah',
		url: 'pendidikan-akhir-diniyah',
		label: 'Pendidikan Akhir Diniyah',
		style: 'single',
		column: 1,
	},
	{
		state: 'pa_Formal',
		url: 'pendidikan-akhir-formal',
		label: 'Pendidikan Akhir Formal',
		style: 'single',
		column: 1,
	},
	{
		state: 'takzirSantri',
		url: 'takzir-santri',
		label: 'Takzir Santri',
		style: 'single',
		column: 1,
	},
	{
		state: 'status',
		url: 'status',
		label: 'Status',
		style: 'single',
		column: 1,
	},
	{
		state: 'sifatIzin',
		label: 'Sifat Izin',
		style: 'single',
		column: 1,
	},
	{
		state: 'keperluanIzin',
		url: 'keperluan-izin',
		label: 'Keperluan Izin',
		style: 'single',
		column: 1,
	},
	{
		state: 'tatibSantri',
		url: 'tatib-santri',
		label: 'Tatib Santri',
		style: 'double',
		column: 2,
	},
	{
		state: 'tahunAjaran',
		url: 'tahun-ajaran',
		label: 'Tahun Ajaran',
		style: 'double',
		column: 2,
	},
	{
		state: 'iuran',
		url: 'iuran',
		label: 'Iuran',
		style: 'double',
		column: 2,
	},
	// { url: 'tingkat-pendidikan', label: 'Tingkat Pendidikan', style: 'two' },
];

const listData = Object.values(data).sort((a, b) => {
	return a.label > b.label ? 1 : -1;
});

export default listData;
