on:
    push:
        branches:
            - main

name: 🚀 Deploy website on push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Setup Nodejs
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build PWA
              run: npx quasar build -m pwa

            - name: Deploy to Shared Hosting
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: demangan.net
                  username: ${{ secrets.ftp_username }}
                  password: ${{ secrets.ftp_password }}
                  port: 65002
                  server-dir: ./dev/
                  local-dir: ./dist/pwa/

            # - name: Deploy to GitHub Pages
            #   uses: JamesIves/github-pages-deploy-action@v4
            #   with:
            #       folder: dist/pwa
            #       clean: true
