on:
    push:
        branches:
            - main
name: 🚀 Deploy website on push
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            # - name: Setup Nodejs
            #   uses: actions/setup-node@v3
            #   with:
            #       node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build PWA
              run: npx quasar build -m pwa

            - name: Deploy to Shared Hosting
              uses: SamKirkland/FTP-Deploy-Action@v4.3.4
              with:
                  server: demangan.net
                  username: ${{ secrets.ftp_username }}
                  password: ${{ secrets.ftp_password }}
                  #   server-dir: ./stage/
                  local-dir: ./dist/pwa/
            # - name: Move "./stage/" to "/"
            #   run: |
            #       mv /stage/* /
            # - name: Move files
            #   run: |
            #       php -r "foreach(glob('/stage/*') as \$file) { rename(\$file, basename(\$file)); }"
            #   php -r "foreach(glob('/stage/*') as \$file) { $newPath = '../' . basename($file); rename($file, $newPath); }"

    # move-files:
    #     runs-on: ubuntu-latest
    #     steps:
    #         - name: Move stage to root
    #           run: |
    #               mv /stage/* /
